{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "           AssertionError: Unexpected message in Update Contribution: Contribution updated successfully.\n           assert 'Contribution...successfully.' == 'Transaction ...successfully.'\n             \n             - Transaction updated successfully.\n             ? ^ ^^^^^\n             + Contribution updated successfully.\n             ? ^^^^ ^^^\n", "test_name": "test_add_contribution", "rerun": "0"}}, "suite_name": "main/test_transactions.py"}}}, "date": "December 09, 2024", "start_time": 1733743462.0063505, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}