{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "           TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\n       urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000025DD1B23E30>, 'Connection to cfs-admin-dev.tgstechnology.net timed out. (connect timeout=None)')\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cfs-admin-dev.tgstechnology.net', port=443): Max retries exceeded with url: /api/Admin/Notification/getAllNotificationType (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025DD1B23E30>, 'Connection to cfs-admin-dev.tgstechnology.net timed out. (connect timeout=None)'))\n               requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='cfs-admin-dev.tgstechnology.net', port=443): Max retries exceeded with url: /api/Admin/Notification/getAllNotificationType (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025DD1B23E30>, 'Connection to cfs-admin-dev.tgstechnology.net timed out. (connect timeout=None)'))\n", "test_name": "test_get_notification_type", "rerun": "0"}, "1": {"status": "FAIL", "message": "           TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\n       urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000025DD1BD7950>, 'Connection to cfs-admin-dev.tgstechnology.net timed out. (connect timeout=None)')\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cfs-admin-dev.tgstechnology.net', port=443): Max retries exceeded with url: /api/Admin/Notification/gettAllNotificationViewStatus (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025DD1BD7950>, 'Connection to cfs-admin-dev.tgstechnology.net timed out. (connect timeout=None)'))\n               requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='cfs-admin-dev.tgstechnology.net', port=443): Max retries exceeded with url: /api/Admin/Notification/gettAllNotificationViewStatus (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025DD1BD7950>, 'Connection to cfs-admin-dev.tgstechnology.net timed out. (connect timeout=None)'))\n", "test_name": "test_get_notification_status", "rerun": "0"}}, "suite_name": "main/test_demo.py"}}}, "date": "May 30, 2024", "start_time": 1717064469.010431, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}